"""adding manager status column in the leave table

Revision ID: 04df9c17bdca
Revises: 64c32a5b110a
Create Date: 2025-07-04 16:45:29.608314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04df9c17bdca'
down_revision: Union[str, None] = '64c32a5b110a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('manager_status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='leavestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'manager_status')
    # ### end Alembic commands ###
