"""initial migration

Revision ID: 0a00c5c5dd45
Revises: ac131016ae8d
Create Date: 2025-06-20 11:50:37.331817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a00c5c5dd45'
down_revision: Union[str, None] = 'ac131016ae8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TimeTracker',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('punch_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('punch_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('activity', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('timetracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetracker',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('punch_in', mysql.DATETIME(), nullable=True),
    sa.Column('punch_out', mysql.DATETIME(), nullable=True),
    sa.Column('duration', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('activity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='timetracker_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('TimeTracker')
    # ### end Alembic commands ###
