"""adding time tracker id as a fk in the break logs table

Revision ID: 1d7bc1aaae19
Revises: 55ed7455a133
Create Date: 2025-07-14 10:50:47.653124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d7bc1aaae19'
down_revision: Union[str, None] = '55ed7455a133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BreakLog',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('time_tracker_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('break_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('break_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['time_tracker_id'], ['TimeTracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BreakLog')
    # ### end Alembic commands ###
