"""adding reason column in the leave table

Revision ID: 22cf419430dd
Revises: c40295ecb2c2
Create Date: 2025-07-09 11:59:13.514314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cf419430dd'
down_revision: Union[str, None] = 'c40295ecb2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('hr_rejection_reason', sa.String(length=255), nullable=True))
    op.add_column('leaves', sa.Column('manager_rejection_reason', sa.String(length=255), nullable=True))
    op.add_column('leaves', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'updated_at')
    op.drop_column('leaves', 'manager_rejection_reason')
    op.drop_column('leaves', 'hr_rejection_reason')
    # ### end Alembic commands ###
