"""fix: varchar length for duration in work_logs

Revision ID: 4b2d41d3cb09
Revises: b156cb1b86b3
Create Date: 2025-07-14 16:42:58.984909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b2d41d3cb09'
down_revision: Union[str, None] = 'b156cb1b86b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_logs',
    sa.Column('id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('time_tracker_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['time_tracker_id'], ['TimeTracker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_logs')
    # ### end Alembic commands ###
