"""Adding user id as fk in leave table

Revision ID: 563624693eb9
Revises: 784182f2310b
Create Date: 2025-07-02 15:36:37.757351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '563624693eb9'
down_revision: Union[str, None] = '784182f2310b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('manager_id', mysql.VARCHAR(length=512), nullable=True))
    op.create_foreign_key(None, 'leaves', 'users', ['manager_id'], ['id'])
    op.alter_column('organizations', 'id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('organizations', 'org_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('organizations', 'email',
               existing_type=mysql.VARCHAR(length=90),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('organizations', 'role_id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('organizations', 'org_type_id',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'org_type_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('organizations', 'role_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('organizations', 'email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=90),
               existing_nullable=True)
    op.alter_column('organizations', 'org_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'manager_id')
    # ### end Alembic commands ###
