"""removing the break time column from the table

Revision ID: 59dd95af0b51
Revises: c8f19dd04e3d
Create Date: 2025-07-03 13:51:55.529570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59dd95af0b51'
down_revision: Union[str, None] = 'c8f19dd04e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeTracker', 'break_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeTracker', sa.Column('break_start', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
