"""removing otp column from the user table

Revision ID: 67d5f7d4ccb5
Revises: fb4d64b68322
Create Date: 2025-06-19 12:15:42.122316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67d5f7d4ccb5'
down_revision: Union[str, None] = 'fb4d64b68322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('otp', sa.Integer(), nullable=True))
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'otp')
    # ### end Alembic commands ###
