"""adding activity column in the table

Revision ID: 8865be9c74ba
Revises: 4b2d41d3cb09
Create Date: 2025-07-14 17:01:15.492383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8865be9c74ba'
down_revision: Union[str, None] = '4b2d41d3cb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeTracker', sa.Column('activity', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeTracker', 'activity')
    # ### end Alembic commands ###
