"""removing org id column from the department table

Revision ID: 96e27a7a70f1
Revises: 03c1aa8af69e
Create Date: 2025-07-02 12:51:10.541483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96e27a7a70f1'
down_revision: Union[str, None] = '03c1aa8af69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('org_id', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
