"""removing two unused column from the time tracker table

Revision ID: b156cb1b86b3
Revises: 1d7bc1aaae19
Create Date: 2025-07-14 15:12:55.288994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b156cb1b86b3'
down_revision: Union[str, None] = '1d7bc1aaae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeTracker', 'break_start')
    op.drop_column('TimeTracker', 'activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeTracker', sa.Column('activity', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('TimeTracker', sa.Column('break_start', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
