"""adding resume time column in the table

Revision ID: c09de8402fc5
Revises: 33405b0f63ed
Create Date: 2025-07-14 17:46:56.678159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09de8402fc5'
down_revision: Union[str, None] = '33405b0f63ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeTracker', sa.Column('resume_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeTracker', 'resume_time')
    # ### end Alembic commands ###
