"""adding separate status column for the hr and manager

Revision ID: c40295ecb2c2
Revises: 04df9c17bdca
Create Date: 2025-07-08 14:04:57.970867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40295ecb2c2'
down_revision: Union[str, None] = '04df9c17bdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('hr_status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='leavestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'hr_status')
    # ### end Alembic commands ###
