"""Adding total break column in the time trackker table

Revision ID: c68b9b9fb1d8
Revises: 59dd95af0b51
Create Date: 2025-07-03 13:54:00.482408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68b9b9fb1d8'
down_revision: Union[str, None] = '59dd95af0b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeTracker', sa.Column('break_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('TimeTracker', sa.Column('total_break_duration', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeTracker', 'total_break_duration')
    op.drop_column('TimeTracker', 'break_start')
    # ### end Alembic commands ###
