"""adding org id as fk in the department table

Revision ID: e152c2bcf2da
Revises: 96e27a7a70f1
Create Date: 2025-07-02 12:54:40.871577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e152c2bcf2da'
down_revision: Union[str, None] = '96e27a7a70f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('organization_id', mysql.VARCHAR(length=512), nullable=False))
    op.create_foreign_key(None, 'departments', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'organization_id')
    # ### end Alembic commands ###
