"""adding role id as fk in org table

Revision ID: fb4d64b68322
Revises: 51705075efc6
Create Date: 2025-06-18 13:59:50.775630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb4d64b68322'
down_revision: Union[str, None] = '51705075efc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('role_id', mysql.VARCHAR(length=512), nullable=False))
    op.create_foreign_key(None, 'organizations', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'role_id')
    # ### end Alembic commands ###
